### **What is NumPy?**
NumPy, short for Numerical Python, is a fundamental Python package for scientific computing.
<br>It is a high-performance package for multidimensional array calculations.

### **Why use NumPy?**
Lists serve the purpose of arrays in Python but they are slow.
<br>NumPy arrays are faster and provide "ndarray" multiple dimensions.
<br>NumPy has many functions for "ndarray" calculations.

For more information about NumPy, check the below link:
<br> https://numpy.org/doc/

To use NumPy the Package should be installed:
<br>pip install numpy

Then import NumPy, "np" is the common Numpy alias.

In [1]:
import numpy as np

#### **1-D arrays:**

In [2]:
# Creating an array from a list, which is a horizontal vector:
my_array_list = np.array([2, 3, 4])

my_array_list

array([2, 3, 4])

In [3]:
print(my_array_list)
print(type(my_array_list))
print(my_array_list.shape)

[2 3 4]
<class 'numpy.ndarray'>
(3,)


In [4]:
# Creating a 1-D array from a tuple, which is a horizontal vector:
my_array_tuple = np.array((2, 3, 4))

print(my_array_tuple)
print(type(my_array_tuple))
print(my_array_tuple.shape)

[2 3 4]
<class 'numpy.ndarray'>
(3,)


In [5]:
# Creating a 1-D array, a vertical vector::
one_column = np.array([[2], [3], [6]])

print(one_column)
print(one_column.shape)

[[2]
 [3]
 [6]]
(3, 1)


**You can use the "len" function with 1-D array:**

In [6]:
# With a horizontal vector you will get the first dimension:
print(len(my_array_tuple))

3


In [7]:
# With a vertical vector you will get the first dimension:
print(len(one_column))

3


**NumPy performs vectorized operations:**
<br>That means it applies operations element-wise.

In [8]:
# Let's take an example:
vector_list1 = [1, 2, 3, 4]
vector_list2 = [5, 6, 7, 8]

In [9]:
# To multiply two lists element-wise:
vector_list_multipy = [vector_list1[i] * vector_list2[i] for i in range(len(vector_list1))]

print(vector_list_multipy)

[5, 12, 21, 32]


In [10]:
# To multiply two NumPy arrays element-wise:
numpy_list1 = np.array([1, 2, 3, 4])
numpy_list2 = np.array([5, 6, 7, 8])

vector_numpy_multiply = numpy_list1 * numpy_list2

print(vector_numpy_multiply)

[ 5 12 21 32]


In [11]:
# To add two lists element-wise:
vector_list_add = [vector_list1[i] + vector_list2[i] for i in range(len(vector_list1))]

print(vector_list_add)

[6, 8, 10, 12]


In [12]:
# To add two NumPy arrays element-wise:
vector_numpy_add = numpy_list1 + numpy_list2

print(vector_numpy_add)

[ 6  8 10 12]


***NumPy arrays are more efficient than lists because there is no need to use a "for" loop.***

### **Creating multiple dimension arrays:**

#### **1. 2-D arrays:**

In [13]:
# shape 2 rows x 3 columns
array_2x3 = np.array([[1, 2, 3],
                      [4, 2, 6]])
print(array_2x3)
print()
print(f"Shape:{array_2x3.shape}")

[[1 2 3]
 [4 2 6]]

Shape:(2, 3)


In [14]:
# shape 4 rows x 3 columns
array_4x3 = np.array([[1, 2, 3],
                      [4, 2, 6],
                      [4, 2, 6],
                      [4, 2, 6]])
print(array_4x3)
print()
print(f"Shape:{array_4x3.shape}")

[[1 2 3]
 [4 2 6]
 [4 2 6]
 [4 2 6]]

Shape:(4, 3)


**You can use the "len" function with 2-D array:**

In [15]:
# shape 2 rows x 3 columns, you will get the first dimension which is 2
print(len(array_2x3))

2


In [16]:
# shape 4 rows x 3 columns, you will get the first dimension which is 4
print(len(array_4x3))

4


#### **2. 3-D arrays**

In a NumPy array with the 3-D shape (3, 2, 4):
<br>The (4) dimension represents the columns.
<br>The (2) dimension represents the rows.
<br>The (3) dimension represents the number of 2D arrays (or "layers") stacked along the first axis.

<center><img src="dimensions.jpg" width="320" height="320"/><center>

In [28]:
# The shape is: 3 layers of 2-D arrays each has 2 rows and 4 columns
array_3x2x4 = np.array([
    [[3, 2, 5, 4],
     [6, 7, 8, 9]],

    [[12, 23, 62, 57],
     [14, 55, 86, 74]],
    
    [[312, 253, 662, 578],
     [144, 855, 986, 274]]
     
],)

print(array_3x2x4)
print()
print(f"Shape:{array_3x2x4.shape}")

[[[  3   2   5   4]
  [  6   7   8   9]]

 [[ 12  23  62  57]
  [ 14  55  86  74]]

 [[312 253 662 578]
  [144 855 986 274]]]

Shape:(3, 2, 4)


**Another 3-D array:**

In [29]:
# The shape is: 2 layers of 1-D arrays each has 3 rows and 1 columns
array_2x3x1 = np.array([
    [[3],
     [7],
     [8]],

    [[12],
     [14],
     [67]],
     
])

print(array_2x3x1)
print()
print(f"Shape:{array_2x3x1.shape}")

[[[ 3]
  [ 7]
  [ 8]]

 [[12]
  [14]
  [67]]]

Shape:(2, 3, 1)


In [30]:
# The shape is: 2 layers of 1-D arrays each has 1 row and 3 columns
array_2x1x3 = np.array([
    [[3, 7, 8]],

    [[12, 14, 67]],   
])

print(array_2x1x3)
print()
print(f"Shape:{array_2x1x3.shape}")

[[[ 3  7  8]]

 [[12 14 67]]]

Shape:(2, 1, 3)


**You can use the "len" function with 3-D array:**

In [31]:
# shape 3 x 2 x 4, you will get the first dimension which is 3
print(len(array_3x2x4))

3


In [32]:
 # shape 2 x 1 x 3, you will get the first dimension which is 2
print(len(array_2x1x3))

2
