### **"copy()" Method:**
"copy" is used to copy an array and create a new array, it owns the data; any changes made to the original array will not change the copy.
<br> The copy and the original arrays are different objects

In [1]:
import numpy as np

In [2]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

copy_numbers = numbers.copy()

numbers[1] = 10
copy_numbers[1] = 20

print(numbers)
print(copy_numbers)

[ 1 10  3  4  5  6  7  8  9]
[ 1 20  3  4  5  6  7  8  9]


In [3]:
# To check that the "numbers" and the "copy_numbers" own the data,
# use the "base" object and it should return "None".
# The "base" object checks if the memory is from another object.

print(numbers.base)
print(copy_numbers.base)

None
None


### **"view()" Method:**
"view" is used to create a view of an array; it doesn't own the data, and any changes made to the original array will change the view.
<br> The view and the original arrays share the same memory.

In [4]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

view_numbers = nums.view()

nums[1] = 10
view_numbers[2] = 100

print(view_numbers)
print(nums)

[  1  10 100   4   5   6   7   8   9]
[  1  10 100   4   5   6   7   8   9]


In [5]:
# Checking the "base":
print(view_numbers.base)
print(nums.base)

[  1  10 100   4   5   6   7   8   9]
None


##### **Why do we use the "view" method?**
Because the view and the original array share the same memory, creating a view is more efficient than creating a copy:

In [6]:
# If we want to create a different data type:
num_int16 = nums.view(np.int16)
print(num_int16.dtype)
print(nums.dtype)

int16
int64


In [7]:
# Checking the "base":
print(num_int16.base)
print(nums.base)

[  1  10 100   4   5   6   7   8   9]
None


In [8]:
# If we want to create different shapes:
array_4x3 = np.array([[7, 72, 3],
                      [4, 5, 6],
                      [33, 8, 7],
                      [21, 1, 0]])

array_3x4 = array_4x3.view().T
print(array_3x4.shape)
print(array_4x3.shape)

(3, 4)
(4, 3)


In [9]:
# Checking the "base":
print(array_4x3.base)
print(array_3x4.base)

None
[[ 7 72  3]
 [ 4  5  6]
 [33  8  7]
 [21  1  0]]


### **"reshape()" Function:**

The reshape function changes the shape of a NumPy array without changing its data.
<br>It is commonly used to rearrange the data structure for compatibility with specific operations.

##### **Reshape From 1-D to 2-D**
<br> To change the a 1-D array to a 2-D array check the array length, then find the numbers that their multiplication is equal to the array length.
    <br>In our example, then length is 10, I can have and array with:
    <br>2 rows by 5 columns,
    <br>5 rows by 2 columns,
    <br>1 rows by 10 columns,
    <br>10 rows by 1 columns,

In [10]:
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Reshape to 2-D array
# array_2d = array_1d.reshape(2, 5)
array_2d = array_1d.reshape(1, 10)

print(array_2d)

[[ 1  2  3  4  5  6  7  8  9 10]]


##### **Reshape From 1-D to 3-D**
To reshape 1-D array to 3-D array:
<br> 1. Determine the number of arrays in the 3rd dimension:
    <br>For example example, we want 2 arrays.
<br> 2. Get the length of the 1-D array and divide it by 2, which is the number of arrays in the 3rd dimension.
    <br>In our example, 18/2 = 9.
<br> 3. Get the result from step two and change it to rows and columns.
    <br>In our example, I can have 3 rows by 3 columns, their multiplication equals 9.
    <br>Or, I can have 9 rows by 1 column, or 1 row by 9 columns, their multiplication equals 9.    

In [11]:
# Using the "arange" function with the "reshape" function
array_1d_arange = np.arange(18)

# Reshape to 3-D array
array_2x3x3 = array_1d_arange.reshape(2, 3, 3)
array_2x9x1 = array_1d_arange.reshape(2, 9, 1)
array_2x1x9 = array_1d_arange.reshape(2, 1, 9)

# print(array_2x3x3)
# print(array_2x9x1)
print(array_2x1x9)

[[[ 0  1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16 17]]]


##### **To flatten the array:**

In [12]:
# A 2-D array:
array_3x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

array_2d_flatten = array_3x3.reshape(-1)
print(array_2d_flatten)

[1 2 3 4 5 6 7 8 9]


In [13]:
# A 3-D array:
array_2x3x3 = np.array([
    [[ 0,  1,  2,],
     [ 3,  4,  5,],
     [ 6,  7,  8]],

    [[ 9, 10, 11],
     [12, 13, 14],
     [15, 16, 17]]])
                       
array_3d_flatten = array_2x3x3.reshape(-1)
print(array_3d_flatten)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [14]:
# You can use the -1 with any shape and NumPy will calculate the dimension:
array_1d_arange = np.arange(18)

array_2d = array_1d_arange.reshape(-1, 9)
# array_2d = array_1d_arange.reshape(3, -1)
print(array_2d)
print(array_2d.shape)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
(2, 9)


In [15]:
# You can use the -1 with any shape and NumPy will calculate the dimension:
array_1d_arange = np.arange(18)

# array_3d = array_1d_arange.reshape(2, -1, 3)
# array_3d = array_1d_arange.reshape(2, 9, -1)
array_3d = array_1d_arange.reshape(-1, 1, 9)
print(array_3d)
print(array_3d.shape)

[[[ 0  1  2  3  4  5  6  7  8]]

 [[ 9 10 11 12 13 14 15 16 17]]]
(2, 1, 9)


Array flattening is used when you want to reshape a 2-D or 3-D array into different shapes:
<br>1. Flatten the array to 1-D array
<br>2. Use the "reshape" function to rearrange the array into a new shape.

In [16]:
array_2x3x3 = np.array([
    [[ 0,  1,  2,],
     [ 3,  4,  5,],
     [ 6,  7,  8]],

    [[ 9, 10, 11],
     [12, 13, 14],
     [15, 16, 17]]])
                       
array_3d_flatten = array_2x3x3.reshape(-1)
len_array_flat = len(array_3d_flatten)
print(len_array_flat)

18


In [17]:
# Reshape the array into a 2-D array:
array_2d_reshaped = array_3d_flatten.reshape(2, 9)

print(array_2d_reshaped)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]


##### **Does the reshape return a view or a copy?**

In [18]:
#let's check out:
array_1d_arange = np.arange(18)

array_2x3x3 = array_1d_arange.reshape(2, -1, 3)
print(array_2x3x3.base)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


### **"nditer()" Function**
To iterate through the items in a 2-D array or 3-D array you need a nested for loops:

In [19]:
# Let's take an example:
array_2x2x2 = np.array([
    [[ 0,  1],
     [ 3,  4]],

    [[ 9, 10],
     [12, 13]]
])

for array in array_2x2x2:
    for row in array:
        for num in row:
            print(num)

0
1
3
4
9
10
12
13


In [20]:
# Using the "nditer()" function will make it simpler:
for num in np.nditer(array_2x2x2):
    print(num)

0
1
3
4
9
10
12
13
