### **NumPy Joining Arrays:**
#### **1. "concatenate()" function:**
To join multiple arrays we use the "concatenate()" function.
<br>NumPy arrays are joined by the "axis" parameter in the "concatenate()" function.
<br>Let's take an example:

In [1]:
import numpy as np

##### **1-D arrays.**

In [ ]:
nums_one = np.array([66, 77, 88, 99, 100])
nums_two = np.array([11, 22, 33, 44, 55, 98])

nums_1d = np.concatenate((nums_one, nums_two))

print(nums_1d)
print(nums_1d.dtype)

##### **2-D arrays.**
To join two 2-D arrays we use the "axis" parameter.

In [ ]:
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_2x4 = np.array([[57, 72, 93, 88],
                    [84, 45, 26, 66]])

# when "axis=1" that means joining by rows:
nums_2d_row = np.concatenate((one_2x3, two_2x4), axis=1)

print(nums_2d_row)
print(nums_2d_row.dtype)

***Note: Joining arrays by row is possible when the arrays have the same row shapes.***

In [ ]:
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_3x2 = np.array([[57, 72],
                    [84, 45],
                    [93, 88],])

nums_2d_row_not = np.concatenate((one_2x3, two_3x2), axis=1)

print(nums_2d_row_not)

***Note: Joining arrays by rows is not allowed when the arrays have different row shapes.***

In [ ]:
# when "axis=0" that means joining by columns:
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_3x3 = np.array([[57, 72, 88],
                    [84, 45, 32],
                    [93, 88, 65]])

nums_2d_col = np.concatenate((one_2x3, two_3x3), axis=0)

print(nums_2d_col)

***Note: Joining arrays by columns is allowed when the arrays have the same column shapes.***

In [ ]:
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_3x2 = np.array([[57, 72],
                    [84, 45],
                    [93, 88]])

nums_2d_col_not = np.concatenate((one_2x3, two_3x2), axis=0)

print(nums_2d_col_not)

***Note: Joining arrays by columns is not allowed when the arrays have different column shapes.***

##### **3-D arrays.**
To join multiple 3-D arrays, we use the "axis" parameter let's take an example:

In [ ]:
arr1_2x2x2 = np.array([[[1, 2],
                         [3, 4]],
                         
                        [[5, 6],
                         [7, 8]]])

arr2_2x2x2 = np.array([[[96, 100],
                          [41, 16]],
                         
                         [[13, 34],
                          [89, 21]]])

# Concatenate along axis 0, will return 4 arrays in z dimension of size 2x2
conc_axis_0 = np.concatenate((arr1_2x2x2, arr2_2x2x2), axis=0)
print("Concatenate along axis 0:\n", conc_axis_0)
print("Array shape:", conc_axis_0.shape)

In [ ]:
# Concatenate along axis 1 will return 2 arrays in z dimension of size 4x2
arr1_2x2x2 = np.array([[[1, 2],
                         [3, 4]],
                         
                        [[5, 6],
                         [7, 8]]])

arr2_2x2x2 = np.array([[[96, 100],
                          [41, 16]],
                         
                         [[13, 34],
                          [89, 21]]])
conc_axis_1 = np.concatenate((arr1_2x2x2, arr2_2x2x2), axis=1)

print("\nConcatenate along axis 1:\n", conc_axis_1)
print("Array shape:", conc_axis_1.shape)

In [ ]:
# Concatenate along axis 2 will return 2 arrays in z dimension of size 2x4
arr1_2x2x2 = np.array([[[1, 2],
                         [3, 4]],
                         
                        [[5, 6],
                         [7, 8]]])

arr2_2x2x2 = np.array([[[96, 100],
                          [41, 16]],
                         
                         [[13, 34],
                          [89, 21]]])

conc_axis_2 = np.concatenate((arr1_2x2x2, arr2_2x2x2), axis=2)
print("\nConcatenate along axis 2:\n", conc_axis_2)
print("Array shape:", conc_axis_2.shape)

***Note: In 3-D arrays with different shapes, the arrays should have the same numbers of arrays in the 3rd dimension "z":***
<br>***1. Joining arrays by row is possible when the arrays have the same row shapes, with different column shapes.***
<br>***2. Joining arrays by columns is allowed when the arrays have the same column shapes, with different row shapes.***

In [ ]:
arr1_2x2x2 = np.array([[[1, 2],
                         [3, 4]],
                         
                        [[5, 6],
                         [7, 8]]])

arr2_3x2x2 = np.array([[[96, 100],
                          [41, 16]],
                         
                         [[13, 34],
                          [89, 21]],
                       
                        [[13, 34],
                          [89, 21]],
                      ])

conc_axis_3 = np.concatenate((arr1_2x2x2, arr2_3x2x2), axis=0)
print("\nConcatenate along axis 2:\n", conc_axis_3)
print("Array shape:", conc_axis_3.shape)

#### **2. "stack()" function:**
Stacking is done along a new axis, creating a new dimension.

In [ ]:
# 1-D Arrays:
nums_one = np.array([66, 77, 88, 99, 100])
nums_two = np.array([11, 22, 33, 44, 55])

nums_5x2 = np.stack((nums_one, nums_two), axis=1)

print(nums_5x2)

In [ ]:
nums_2x5 = np.stack((nums_one, nums_two), axis=0)

print(nums_2x5)

If the arrays have different shapes Python will raise a "ValueError" exception.

In [3]:
# 2-D Arrays:
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_2x3 = np.array([[57, 72, 93],
                    [84, 45, 26]])

# "axis=0" will create a new 3-D array with two arrays in the 3rd dimension, z-axis: 
nums_2x3x2 = np.stack((one_2x3, two_2x3), axis=0)
print(nums_2x3x2)

[[[ 7  1  3]
  [ 4  5  6]]

 [[57 72 93]
  [84 45 26]]]


In [4]:
# "axis=1" will create a new 3-D array with two arrays in the 3rd dimension, z-axis,
# the arrays are created from each row of each array, respectively:
nums_2x2x3_row = np.stack((one_2x3, two_2x3), axis=1)
print(nums_2x2x3_row)

[[[ 7  1  3]
  [57 72 93]]

 [[ 4  5  6]
  [84 45 26]]]


In [5]:
# "axis=1" will create a new 3-D array with two arrays in the 3rd dimension, z-axis,
# the arrays are created from each row of each array, respectively,
# and then changed to a column:
nums_2x3x2_col = np.stack((one_2x3, two_2x3), axis=2)
print(nums_2x3x2_col)

[[[ 7 57]
  [ 1 72]
  [ 3 93]]

 [[ 4 84]
  [ 5 45]
  [ 6 26]]]


##### **There are other stack functions:**

In [6]:
# "hstack()" stacks along the rows, there is no "axis" parameter
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_2x3 = np.array([[57, 72, 93],
                    [84, 45, 26]])

nums_hstack = np.hstack((one_2x3, two_2x3))
print(nums_hstack)

[[ 7  1  3 57 72 93]
 [ 4  5  6 84 45 26]]


In [7]:
# "vstack()" stacks along the columns, there is no "axis" parameter
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_2x3 = np.array([[57, 72, 93],
                    [84, 45, 26]])

nums_vstack = np.vstack((one_2x3, two_2x3))
print(nums_vstack)

[[ 7  1  3]
 [ 4  5  6]
 [57 72 93]
 [84 45 26]]


In [8]:
# "dstack()" stacks along the 3rd axis (depth, z-axis), there is no "axis" parameter
one_2x3 = np.array([[7, 1, 3],
                    [4, 5, 6]])
two_2x3 = np.array([[57, 72, 93],
                    [84, 45, 26]])

nums_dstack = np.dstack((one_2x3, two_2x3))
print(nums_dstack)

[[[ 7 57]
  [ 1 72]
  [ 3 93]]

 [[ 4 84]
  [ 5 45]
  [ 6 26]]]
