In [1]:
import numpy as np

#### **1. "split()" function:**

In [2]:
# 1-D arrays:
nums = np.array([66, 77, 88, 99, 100, 11, 22, 33, 44, 55, 98, 12])

# Spliting into six arrays:
split_nums_six = np.split(nums, 6)

# Spliting into three arrays:
split_nums_three = np.split(nums, 3)

print("Splitting into six arrays:\n", split_nums_six)
print("Splitting into three arrays:\n", split_nums_three)

Splitting into six arrays:
 [array([66, 77]), array([88, 99]), array([100,  11]), array([22, 33]), array([44, 55]), array([98, 12])]
Splitting into three arrays:
 [array([66, 77, 88, 99]), array([100,  11,  22,  33]), array([44, 55, 98, 12])]


In [3]:
# To get arrays use indexing:
print(split_nums_six[2])

[100  11]


In [ ]:
# 2-D arrays:
array_4x3 = np.array([[57, 72, 88],
                    [84, 45, 32],
                    [93, 88, 65],
                    [67, 21, 94]])

# Spliting into two arrays:
split_2d_two = np.split(array_4x3, 2, axis=0)

print("Splitting into two arrays:\n", split_2d_two)
print(split_2d_two[0].shape)

In [ ]:
array_3x3 = np.array([[57, 72, 88],
                    [84, 45, 32],
                    [93, 88, 65]])


split_2d_three = np.split(array_3x3, 3, axis=1)

print("Splitting into three arrays:\n", split_2d_three)
print(split_2d_three[0].shape)

In [ ]:
# 3-D arrays:
arr_2x2x4 = np.array([
    [[96, 100, 4, 77],
     [41, 16, 9, 12]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]]
])

# Spliting into three arrays, along the z-axis, axis=0 is the default axis:
split_3d_three = np.split(arr_2x2x4, 3)

print("Splitting into three arrays:\n", split_3d_three)
print(split_3d_three[0].shape)

In [ ]:
# Spliting into two arrays, along the rows, axis=1:
arr_2x2x4 = np.array([
    [[96, 100, 4, 77],
     [41, 16, 9, 12]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]]
])

split_3d_two = np.split(arr_2x2x4, 2, axis=1)

print("Splitting into three arrays:\n", split_3d_two)
print(split_3d_two[0].shape)

In [ ]:
# Spliting into 4 arrays, along the columns, axis=2:
arr_2x2x4 = np.array([
    [[96, 100, 4, 77],
     [41, 16, 9, 12]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]]
])

split_3d_four = np.split(arr_2x2x4, 2, axis=2)

print("Splitting into three arrays:\n", split_3d_four)
print(split_3d_four[0].shape)

***Note:Similar to stack there are available, hsplit(), vsplit(), and dsplit().***

#### **2. "where()" function:**
The ""where()" function is used to search for items in an array.

In [2]:
array_4x3 = np.array([[57, 72, 88],
                    [84, 45, 32],
                    [93, 43, 65],
                    [88, 21, 89]])

find_item_88= np.where(array_4x3 == 88)

print(find_item_88)

(array([0, 3]), array([2, 0]))


In [3]:
find_items_gt_88 = np.where(array_4x3 > 88)

print(find_items_gt_88)

(array([2, 3]), array([0, 2]))


To get the items:

In [4]:
item_88 = array_4x3[find_item_88]
items_gt_88 = array_4x3[find_items_gt_88]

print(item_88)
print(items_gt_88)

[88 88]
[93 89]


The first array is the indexes of the rows while the second is the indexes of the columns.

In [5]:
array_4x3 = np.array([[57, 72, 88],
                    [84, 45, 32],
                    [93, 43, 65],
                    [88, 21, 89]])

even_numbers_indexes_2d = np.where(array_4x3%2 == 0)
get_even_numbers_2d = array_4x3[even_numbers_indexes_2d]

print(even_numbers_indexes_2d)
print(get_even_numbers_2d)

(array([0, 0, 1, 1, 3]), array([1, 2, 0, 2, 0]))
[72 88 84 32 88]


In [6]:
arr_2x2x4 = np.array([
    [[96, 100, 4, 77],
     [41, 16, 9, 12]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]],
                      
    [[13, 34, 43, 65],
     [89, 21, 90,33]]
])

odd_numbers_indexes_3d = np.where(arr_2x2x4%2 != 0)
get_odd_numbers_3d = arr_2x2x4[odd_numbers_indexes_3d]

print(odd_numbers_indexes_3d)
print(get_odd_numbers_3d)

(array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]), array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]), array([3, 0, 2, 0, 2, 3, 0, 1, 3, 0, 2, 3, 0, 1, 3]))
[77 41  9 13 43 65 89 21 33 13 43 65 89 21 33]


The first array is the (number of arrays) 3rd dimension indexes, the second is the indexes of the rows, and the third is the indexes of the columns.

The same thing for the single dimension array:

In [7]:
# 1-D arrays:
nums = np.array([66, 77, 88, 99, 100, 11, 22, 33, 44, 55, 98, 12])

item_1_d_indexes = np.where(nums >= 66)
get_1_d_items = nums[item_1_d_indexes]

print(item_1_d_indexes)
print(get_1_d_items)

(array([ 0,  1,  2,  3,  4, 10]),)
[ 66  77  88  99 100  98]


You can use "where()" function to replace items in array:

In [8]:
nums = np.array([66, 77, 88, 99, 100, 11, 22, 33, 44, 55, 98, 12])

# Use np.where to replace values
# If the condition (value > 66) is true, replace with 3, otherwise, replace with 4, (if False)
result = np.where(nums > 66, 3, 4)

print("Original array:", nums)
print("Resultant array:", result)

Original array: [ 66  77  88  99 100  11  22  33  44  55  98  12]
Resultant array: [4 3 3 3 3 4 4 4 4 4 3 4]


As shown above, when replacing items, you get the results directly; you don't get the indices arrays.

When replacing a value, both values for true and false results should be added, if not an exception will be raised.

In [10]:
nums = np.array([66, 77, 88, 99, 100, 11, 22, 33, 44, 55, 98, 12])

# Keep items and change items, we do the following:
# result = np.where(nums > 66, nums, nums*2)
result = np.where(nums > 66, nums*2, nums)
print("Original array:", nums)
print("Resultant array:", result)

Original array: [ 66  77  88  99 100  11  22  33  44  55  98  12]
Resultant array: [ 66 154 176 198 200  11  22  33  44  55 196  12]


In [11]:
x = np.array([
    [0],
    [1],
    [2]])

y = np.array([[0, 1, 2, 3]])

print(np.where(x < y, x, 10 + y))

[[10  0  0  0]
 [10 11  1  1]
 [10 11 12  2]]
