### **"ufunc" in NumPy:**
"ufunc" stands for universal functions, which are NumPy functions that operate on the n-D array object.
<br> Let's take an example:

#### **1. Mathematical functions:**
There are many mathematical functions in NumPy, such as:
<br> 1. Trigonometric functions, such as: "sin", "cos", "tan", etc.
<br> 2. Rounding functions, such as: "round", "around", "rint", etc.
<br> 3. Arithmetic operations, such as: "add", "subtract", "divide", etc. 
<br> 4. Sums, products, differences such as: "sum", "prod", "diff", etc.
<br> 5. etc.
<br> You can check out all the mathematical functions using this link:
<br> https://numpy.org/doc/stable/reference/routines.math.html#mathematical-functions

In [ ]:
import numpy as np

As mentioned before, we can perform mathematical calculations in NumPy, element-wise.

In [ ]:
# In a 1-D array vectorized operations:
nums_one = np.array([1, 2, 3, 4, 5])
nums_two = np.array([6, 7, 8, 9, 10])

# Using the "add" function:
print(np.add(nums_one, nums_two))

# It is the same as "+":
print(nums_one + nums_two)

[ 7  9 11 13 15]
[ 7  9 11 13 15]


In [ ]:
# In a 2-D array element-wise operations:
nums_one_2D = np.array([1, 2, 3, 4, 5, 0]).reshape((2,3))
nums_two_2D = np.array([6, 7, 8, 9, 10, 0]).reshape((2,3))

print(nums_one_2D)
print("************")
print(nums_two_2D)
print("************")
# Using the "add" function:
print("Results:")
print("************")
print(np.multiply(nums_one_2D, nums_two_2D))
print("************")
# It is the same as "*":
print(nums_one_2D * nums_two_2D)

[[1 2 3]
 [4 5 0]]
************
[[ 6  7  8]
 [ 9 10  0]]
************
Results:
************
[[ 6 14 24]
 [36 50  0]]
************
[[ 6 14 24]
 [36 50  0]]


In [ ]:
# 1-D array using "prod" and "sum" functions:
nums_one = np.array([1, 2, 3, 4, 5, 1])

# Using the "add" function:
print("Results:")
print("************")

# The prod function will return a scaler, the product of
# all items in an array.
print(np.prod(nums_one))
print("************")
print(np.sum(nums_one))

Results:
************
120
************
16


In [ ]:
# Use the "prod" function for the product over an axis:
nums_one = np.array([1, 2, 3, 4, 5])
nums_two = np.array([6, 7, 8, 9, 1])

print("Results:")
print("************")
print("Axis = 1: ", np.prod([nums_one, nums_two], axis=1))
print("************")
print("Axis = 0: ", np.prod([nums_one, nums_two], axis=0))

Results:
************
Axis = 1:  [ 120 3024]
************
Axis = 0:  [ 6 14 24 36  5]
