### **2. "unique()" function:**
This function returns the unique elements in an array.

#### **a. Returns a sorted array with unique elements without duplicates.**

In [1]:
import numpy as np

In [2]:
array_1d = np.array(["d", "c", "b", "f", "b", "c", "a", "b", "e"])
unique_elements_1D = np.unique(array_1d)

print(unique_elements_1D)

['a' 'b' 'c' 'd' 'e' 'f']


#### **b. Returns the unique elements and their indices in the original array.**

In [3]:
array_1d = np.array(["d", "c", "b", "f", "b", "c", "a", "b", "e"])
unique_elements_1D, unique_indices = np.unique(array_1d, return_index=True)

print(unique_elements_1D)
print(unique_indices)

['a' 'b' 'c' 'd' 'e' 'f']
[6 2 1 0 8 3]


#### **c. Returns the unique elements and counts their repetition.**

In [4]:
array_1d = np.array(["d", "c", "b", "f", "b", "c", "a", "b", "e"])
unique_elements_1D, unique_counts = np.unique(array_1d, return_counts=True)

print(unique_elements_1D)
print(unique_counts)

['a' 'b' 'c' 'd' 'e' 'f']
[1 3 2 1 1 1]


#### **d. Returns the unique elements and their inverse indices.**

In [5]:
array_1d = np.array(["d", "c", "b", "f", "b", "c", "a", "b", "e"])
unique_elements_1D, unique_indices = np.unique(array_1d, return_inverse=True)

print(unique_elements_1D)
print(unique_indices)

['a' 'b' 'c' 'd' 'e' 'f']
[3 2 1 5 1 2 0 1 4]


The first index 3, is the index of the "d" element in the unique array, and because the "d" index is 0 in the original array, the 3 is the first element in the inverse index array.

This is used to reconstruct the original array by mapping the unique values to their occurrences in the original array if you don't have the original array.
Such as data compression, if you're working with large arrays, storing unique values and inverse indices can reduce memory usage compared to storing the entire array, especially when there are many duplicate elements.

In [6]:
print(unique_elements_1D[unique_indices])

['d' 'c' 'b' 'f' 'b' 'c' 'a' 'b' 'e']


### **"unique_all() function:**
This function returns all the above-mentioned parameters:

In [7]:
array_1d = np.array(["d", "c", "b", "f", "b", "c", "a", "b", "e"])
unique_elements_1D = np.unique_all(array_1d)

print("Sorted array with unique elements:", unique_elements_1D.values)
print("Unique elements indexes in the original array", unique_elements_1D.indices)
print("Count the unique elemenet in the original array.", unique_elements_1D.counts)
print("Unique elemenet inverse indices in the original array.", unique_elements_1D.inverse_indices)

Sorted array with unique elements: ['a' 'b' 'c' 'd' 'e' 'f']
Unique elements indexes in the original array [6 2 1 0 8 3]
Count the unique elemenet in the original array. [1 3 2 1 1 1]
Unique elemenet inverse indices in the original array. [3 2 1 5 1 2 0 1 4]


### **"unique_values() function:**
This function returns the unique elements only.

In [8]:
array_1d = np.array(["d", "c", "b", "f", "b", "c", "a", "b", "e"])
unique_elements_1D = np.unique_values(array_1d)

print("Sorted array with unique elements:", unique_elements_1D)

Sorted array with unique elements: ['a' 'b' 'c' 'd' 'e' 'f']


### **"unique" function with 2-D arrays:**

In [9]:
array_2x3 = np.array([[3, 4, 3],
                     [4, 5, 2]])

unique_elements_2x3 = np.unique(array_2x3)

print(unique_elements_2x3)

[2 3 4 5]


In [10]:
# Find unique rows:
array_3x3 = np.array([[2, 3, 4],
                      [1, 0, 0],
                      [2, 3, 4]])
unique_elements_3x3 = np.unique(array_3x3, axis=0)

print(unique_elements_3x3)

[[1 0 0]
 [2 3 4]]


In [11]:
# Find unique columns:
array_3x4 = np.array([[2, 4, 4, 5],
                      [1, 0, 0, 2],
                      [2, 4, 4, 5]])
unique_elements_3x4= np.unique(array_3x4, axis=1)

print(unique_elements_3x4)

[[2 4 5]
 [1 0 2]
 [2 4 5]]


**The 3-D arrays are the same as the 2-D arrays, you can do the same steps we did above.
<br> You can try it yourself.**